services:
  postgres:
    image: postgres:17
    container_name: nprs_postgres
    restart: always
    ports:
      - "5432:5432"  # Expose PostgreSQL to your host network
    environment:
      POSTGRES_USER: nprs_user
      POSTGRES_PASSWORD: cris_nprs
      POSTGRES_DB: nprs_db
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - nprs_net

volumes:
  pg_data:

networks:
  nprs_net:
    driver: bridge